//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "character")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub name: String,
    pub show_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::character_show::Entity")]
    CharacterShow,
    #[sea_orm(has_many = "super::quote::Entity")]
    Quote,
    #[sea_orm(
        belongs_to = "super::show::Entity",
        from = "Column::ShowId",
        to = "super::show::Column::Id",
        on_update = "NoAction",
        on_delete = "NoAction"
    )]
    Show,
}

impl Related<super::character_show::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::CharacterShow.def()
    }
}

impl Related<super::quote::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Quote.def()
    }
}

impl Related<super::show::Entity> for Entity {
    fn to() -> RelationDef {
        super::character_show::Relation::Show.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::character_show::Relation::Character.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
