//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

pub mod prelude;

pub mod character;
pub mod character_show;
pub mod customers;
pub mod episode;
pub mod invoices;
pub mod quote;
pub mod revenue;
pub mod season;
pub mod show;
pub mod users;
