//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

pub use super::character::Entity as Character;
pub use super::character_show::Entity as CharacterShow;
pub use super::episode::Entity as Episode;
pub use super::quote::Entity as Quote;
pub use super::quote_part::Entity as QuotePart;
pub use super::season::Entity as Season;
pub use super::show::Entity as Show;
