name: main
on:
  push:
    branches:
      - dev
env:
  VERCEL_ORG_ID: ${{secrets.QUOTED_API_VERCELL_ORG_ID}}
  VERCEL_PROJECT_ID: ${{secrets.QUOTED_API_VERCEL_PROJECT_ID}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: moonrepo/setup-rust@v1
        with:
          targets: 'x86_64-unknown-linux-musl'
      - name: Install musl-tools to provide musl-gcc
        uses: awalsh128/cache-apt-pkgs-action@v2
        with:
          packages: musl-tools
        version: "1.0"
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Write cargo config (forces a specific target)
        run: mkdir .cargo && printf "[build]\ntarget = \"x86_64-unknown-linux-musl\"\n" > .cargo/config.toml
      - name: Pull Vercel Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build
        run: vc build --prod --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy
        run: vc deploy --prod --prebuilt --token=${{ secrets.VERCEL_TOKEN }}