name: main
on:
  push:
    branches:
      - dev
env:
  VERCEL_ORG_ID: ${{secrets.QUOTED_API_VERCELL_ORG_ID}}
  VERCEL_PROJECT_ID: ${{secrets.QUOTED_API_VERCEL_PROJECT_ID}}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Build
        run: vc build --prod --token=${{ secrets.VERCEL_TOKEN }}
      
      - name: Deploy
        run: vc deploy --prod --prebuilt --token=${{ secrets.VERCEL_TOKEN }}